name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'todo_app/diagrams/**'

env:
  DOCKER_TAG: 'jackiemaw/do-me:latest'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  TF_VAR_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
  TF_VAR_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET }}

jobs:

  deploy_azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: curl -dH -X POST "$(terraform output -raw webhook_URL)"
